spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warmplace
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
    mongodb:
      host: localhost
      port: 27017
      database: warmplace_chat
