spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/warmplace}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      user: ${SPRING_DATA_REDIS_USER:defalut}
      password: ${SPRING_DATA_REDIS_PASSWORD:defalut}
      timeout: 60000
      ssl:
        enabled: true
    mongodb:
      url : ${SPRING_DATA_MONGODB_URL:localhost}
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:warmplace_chat}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

app:
  cors:
    allowed-origin-patterns:
      - "https://warmplace-backend-latest.onrender.com"
      - "http://localhost:5173"
      - "http://localhost:8080"

jwt:
  secret: ${JWT_SECRET:warmplace-jwt-secret-key-2024-very-long-secret-key-for-security}
  expiration: ${JWT_EXPIRATION:86400000}
